name: BONEH Ministries
favicon: null
layout_spectrum: 0.63839
typography_spectrum: 0.4973179704975337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#da7765'
    - '#2c6b35'
    - '#ffab6a'
    - '#b7cab8'
  brandStrength: 0
  lightness: 1
  saturation: 0.25873367534950376
  rhythmicContrast: 0.75
purpose: []
