typography_spectrum: 0.4973179704975337
color:
  brandColors:
    - '#ffffff'
    - '#da7765'
    - '#2c6b35'
    - '#ffab6a'
    - '#b7cab8'
  brandStrength: 0
  lightness: 1
  saturation: 0.25873367534950376
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63839
analytics:
  google: null
  facebook: null
  twitter: null
name: BONEH Ministries
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: 'Restaurando vidas, a través del amor de Dios'
purpose: []
