name: BONEH Ministries
favicon: null
layout_spectrum: 0.5682462872937322
typography_spectrum: 0.4973179704975337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7359195495955646
  lightness: 0.7047803234308958
  saturation: 0.25873367534950376
  rhythmicContrast: 0.06023045536130667
purpose: []
